/* Search index for the Khuwari docs. The hub (docs.html) searches across every
 * category page through this list; each topic links to its subpage. */
window.KHUWARI_DOCS = [
  // getting started
  { cat: 'Getting started', slug: 'getting-started', id: 'what-is', title: 'What is Khuwari?',
    text: 'Khuwari is a browser based animation tool that fills in the frames between your keyframes using machine learning. You draw or import the important poses, place them on the timeline, and Khuwari generates everything in between. It runs entirely in your browser. The machine learning model is downloaded once, and your art never leaves your machine.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'open-app', title: 'Open the app',
    text: 'The easiest way is to use Khuwari straight from the website at theshovel.rocks/khuwari, in your browser, no install. You can also host it yourself with any static file server and open index.html. From the start screen you can start a new project, load an existing .khuwari file, or try the bundled example project. The example project is the fastest way to see what a finished animation looks like. Load it and press play.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'project-files', title: 'Project files',
    text: 'Projects save as .khuwari files that are easy to version and share. They hold your layers, keyframes, gaps and settings. Use File in the toolbar, then Save project (.khuwari) to download one, and Load project to bring one back.',
    url: 'docs/getting-started.html' },

  // interface
  { cat: 'The interface', slug: 'interface', id: 'assets-panel', title: 'Assets panel',
    text: 'Your image library, on the left. Use Add images to bring in art, then drag images onto the timeline to make keyframes. You can delete images from the panel when you no longer need them.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'preview', title: 'The preview',
    text: 'The large canvas in the center shows the current frame, and the filmstrip under it shows every frame of the animation. Press play to watch it move, or step frame by frame with the arrow keys.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'timeline', title: 'The timeline',
    text: 'Each layer has its own track at the bottom. Keyframes appear as chips, and the space between two keyframes is a gap. Click a chip to select it, drag it to move it, and drag its edges to change how long it holds.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'selection-panel', title: 'Selection panel',
    text: 'Shows the details of whatever you have selected, whether that is a keyframe, a gap or a color dot. This is where you set times, blend modes, inbetweens and dot properties.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'layers', title: 'Layers',
    text: 'The Layer button in the toolbar opens the layer menu. From there you can add a normal layer, add a color layer, rename, hide or remove the active layer. Layers draw from top to bottom, and each one keeps its own keyframes and gaps. Drag layers up and down in the menu to reorder them.',
    url: 'docs/interface.html' },

  // keyframes
  { cat: 'Keyframes', slug: 'keyframes', id: 'add-keyframe', title: 'Add a keyframe',
    text: 'Drag an image from the assets panel onto a layer track at the time you want it. The image becomes a keyframe chip that holds that pose.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'select-inspect', title: 'Select and inspect',
    text: 'Click a chip to select it. The selection panel on the right shows a thumbnail, the exact time, the blend mode, and buttons to replace or delete the frame.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'move-resize', title: 'Move and resize',
    text: 'Drag a chip left or right to change when it happens. Drag its edges to change how long the frame holds before the gap starts. Hold times matter for pacing.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'set-time', title: 'Set the time exactly',
    text: 'With a keyframe selected, enter the time in seconds in the selection panel. Use the playhead and frame counter to find the moment you want.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'replace-delete', title: 'Replace or delete',
    text: 'Select a keyframe and use Replace image to swap in different art, or Delete to remove it. The keyboard shortcut Delete or Backspace also works.',
    url: 'docs/keyframes.html' },

  // gaps & inbetweens
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'what-is-gap', title: 'What is a gap?',
    text: 'The space between two keyframes on the same layer. Click the gap chip on the timeline to open its options in the right panel. The inbetweens are generated there.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'ml', title: 'Machine learning',
    text: 'The default mode. A machine learning model generates the inbetween frames, which gives the most natural motion for complex art. This is where Khuwari shines.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'squash', title: 'Squash and stretch',
    text: 'A stylized deformation for cartoon motion. Choose the amount, the curve (anticipation, impact, ease or linear) and whether to preserve area or volume. Set the amount to auto for a distance based value.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'none', title: 'No inbetweens',
    text: 'No inbetweens at all. The first keyframe simply holds until the next one starts. Good for flashes, cuts and text.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'motion-blur', title: 'Motion blur',
    text: 'A per gap toggle. When on, the inbetweens smear along their motion, and the blur eases in and out with the movement. The intensity slider controls how strong the smear is. It is designed to mask small imperfections in generated frames, and it works on color layers too.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'regenerate', title: 'Regenerate',
    text: 'Inbetweens regenerate automatically whenever your keyframes change. To force a full refresh, use the regenerate button above the timeline, to the right of the play buttons.',
    url: 'docs/gaps.html' },

  // color layers
  { cat: 'Color layers', slug: 'color-layers', id: 'what-they-do', title: 'What they do',
    text: 'A color layer holds dots instead of keyframes. Each dot acts like a smart bucket fill for the layer above it, so you can color in line art without touching the drawing.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'add-place', title: 'Add one and place dots',
    text: 'Use the Layer menu and choose Add color layer. Then click on the canvas to place a dot. The dot fills everything inside the nearest lines of the layer above.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'dot-properties', title: 'Dot properties',
    text: 'Each dot has a fill color, a threshold (how strong a line must be to stop the fill) and a grow radius in pixels, which tucks the color under soft edges. Tune these per dot.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'gradients', title: 'Gradients',
    text: 'Turn on Gradient to give a dot a gradient instead of a flat fill. Choose the gradient color, its height and its direction (top, bottom, left or right).',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'timing', title: 'Timing',
    text: 'Dots only work during the time you set. Use the start and end fields in the right panel, or drag the dot chip on the timeline and drag its edges to resize. Outside that window the dot does nothing.',
    url: 'docs/color-layers.html' },

  // onion skinning
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'what-it-is', title: 'What it is',
    text: 'Onion skinning shows the frames around the current one, so you can see where the motion is heading while you work. It is a toggle, like the view only keyframes button.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'turn-it-on', title: 'Turn it on',
    text: 'The onion button in the transport area toggles it on and off. The small arrow next to it opens the settings popup.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'settings', title: 'Settings',
    text: 'Choose how many frames to show before and after the current one, the ghost opacity, and whether to show ghosts tinted. If you enable tint, pick the tint color and strength.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'saved', title: 'Saved automatically',
    text: 'Your onion skin settings are saved in the browser, so they come back the next time you open Khuwari, even after loading a project.',
    url: 'docs/onion-skinning.html' },

  // blend modes
  { cat: 'Blend modes', slug: 'blend-modes', id: 'per-keyframe', title: 'Per keyframe blending',
    text: 'Each keyframe can use any of 16 blend modes, from multiply and screen to color and luminosity. Set it in the selection panel with a keyframe selected.',
    url: 'docs/blend-modes.html' },

  // export
  { cat: 'Export', slug: 'export', id: 'formats', title: 'Formats',
    text: 'The Export button in the toolbar offers a PNG sequence in a zip, an animated GIF, video in five containers (MP4, WebM, MKV, MOV and MPEG-TS) and the current frame as a single PNG.',
    url: 'docs/export.html' },
  { cat: 'Export', slug: 'export', id: 'resolution', title: 'Resolution',
    text: 'Pick the export resolution from the export menu. Exports run in the background with a progress bar, and you can stop them if you change your mind.',
    url: 'docs/export.html' },

  // settings
  { cat: 'Settings', slug: 'settings', id: 'fps', title: 'FPS',
    text: 'How many frames per second the timeline plays. Lower values are punchier and cheaper to generate, higher values are smoother.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'snap', title: 'Snap to frames',
    text: 'Keeps the playhead and keyframes on whole frames, so times stay tidy. Turn it off for free placement.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'aspect', title: 'Aspect ratio',
    text: 'Follow the first frame, pick a preset such as 16:9 or 1:1, or set a custom size or a manual ratio like 2.35.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'work-size', title: 'Working size',
    text: 'The long edge of the working canvas, from 512 pixels down to 320. Smaller is noticeably faster to generate, and exports still render at full resolution.',
    url: 'docs/settings.html' },

  // keyboard shortcuts
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'playback', title: 'Playback',
    text: 'Space plays or pauses the animation. Left and Right arrows step one frame back or forward.',
    url: 'docs/shortcuts.html' },
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'editing', title: 'Editing',
    text: 'Delete or Backspace deletes the selected keyframe. Shortcuts are ignored while you are typing in a field.',
    url: 'docs/shortcuts.html' },

  // paint
  { cat: 'Paint', slug: 'paint', id: 'what-it-is', title: 'What it is',
    text: 'The paint tool is a full Krita-style drawing workspace built into Khuwari. Sketch, ink and color right inside the editor on layers, with brushes, selection, transform, fill, shapes and more, then drop the result into your animation. Paint-made images stay editable - their layers are saved with the project.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'open', title: 'Open the paint tool',
    text: 'Open the paint tool with the Paint button in the toolbar for a blank canvas, or right-click a keyframe and choose Edit in paint to redraw that pose. Saved drawings land in the asset library and drag onto the timeline like any image. Editing a library image saves automatically when you close.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'tools', title: 'Tools',
    text: 'The paint tool has brush, eraser, selection (rectangle, ellipse or lasso), lasso, move, free transform, flood fill, color picker, line, rectangle, ellipse and crop tools. Each has a keyboard shortcut: B, E, S, L, V, T, G, I, U and C.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'brushes', title: 'Brushes',
    text: 'A Krita-style brush preset list with size, opacity, hardness and smoothing (stabilizer) options. The bundle ships with Krita default .kpp presets including real brush tips, plus MyPaint .myb brushes. Drop more files into the brushes folder and they load automatically.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'layers', title: 'Layers',
    text: 'Paint layers each have a thumbnail, visibility, opacity and a blend mode. Add, delete, reorder and merge layers, double-click to rename, and paint on the selected layer. The layers are saved with the image, so drawings stay editable after save and reopen.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'color', title: 'Color',
    text: 'The color docker is an HSV color wheel with a saturation/value square, a hue slider and a hex field. The color picker tool grabs a color straight off the canvas.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'onion', title: 'Onion skin in paint',
    text: 'Turn on onion skin while drawing to see the neighboring keyframes as ghosts, with the same before/after counts, opacity and tint as the main viewport. The frame scrubber moves the playhead and the ghosts follow it.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'image-ops', title: 'Canvas and image operations',
    text: 'The Image menu flips or rotates the whole canvas and resizes it, with optional aspect lock and scale content. The crop tool trims to a rectangle. Double-click to re-center, scroll to zoom, and middle-drag or Shift-drag to pan.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'save', title: 'Save your drawing',
    text: 'Save to library adds the drawing to the assets panel, where it drags onto the timeline like any image. Repainting a keyframe updates it in place and regenerates the gaps around it; brand-new drawings are named the first time you add them.',
    url: 'docs/paint.html' },

  // camera
  { cat: 'Camera', slug: 'camera', id: 'what-it-is', title: 'What it is',
    text: 'The camera applies a pan, zoom and rotation to the whole frame on top of your layers, plus lens and film effects: fisheye, film grain, chromatic aberration, vignette and handheld shake. It is non-destructive and applied to the preview and to exports alike. While a Color layer is selected the camera steps aside and the panel locks, so dots land exactly where you click.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'add-key', title: 'Add a camera key',
    text: 'Open the Camera panel, move the playhead, and drag the Pan X, Pan Y, Zoom, Rotation or Effects sliders to add a camera key at that moment. The first key is remembered for the whole timeline so the pose holds before the camera moves. Add key stamps the current values.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'lane', title: 'The Camera track',
    text: 'Camera keys appear as dots on the Camera row under your layers in the timeline. Drag a dot to retime it, double-click to remove it, and use Remove key when the playhead sits on one.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'effects', title: 'The Effects sliders',
    text: 'Five camera effects have intensity sliders from 0 to 100 percent: fisheye warps the frame like a wide lens, chromatic aberration splits red and blue at the edges (gentler at low values), film grain adds a seeded speckle, vignette darkens the corners, and handheld shake adds a smooth low-frequency wobble with its own speed slider. Each is remembered per key and blends between keys.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'interpolation', title: 'Between keys',
    text: 'Every camera value, transforms and effects alike, blends smoothly from key to key. Two keys make a slow push-in or pull-out, or ease an effect in and out. Spacing the keys shapes the easing of the movement.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'export', title: 'Applied to exports',
    text: 'The camera is part of the final composite, so every exported frame includes it, lens effects and all. Use it with squash, motion blur and color layers like the rest of the frame.',
    url: 'docs/camera.html' },

  // audio
  { cat: 'Audio', slug: 'audio', id: 'what-it-is', title: 'What it is',
    text: 'The audio track is a scratch reference track for timing. Load a sound file and it plays in sync with the timeline so you can animate to the beat or to dialogue. It is not part of the export.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'load-remove', title: 'Load and manage audio',
    text: 'The Audio panel in the right column lets you load a sound file, mute it without removing it, or remove it. Load and Remove swap: Load shows when there is no audio, Remove when there is.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'waveform', title: 'The waveform lane',
    text: 'Once audio is loaded, a green waveform appears in a lane under the timeline, aligned with the time ruler. Click anywhere in it to jump the playhead to that moment.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'saved', title: 'Saved with the project',
    text: 'The audio file is stored inside the .khuwari project, so it comes back when you reopen the file. Everything is stored locally on your machine.',
    url: 'docs/audio.html' },

  // undo & redo
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'undo-redo', title: 'Undo and redo',
    text: 'The transport at the bottom of the timeline has Undo and Redo buttons. Edits to keyframes, gaps, layers, dots, camera and audio all land on the history stack.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'shortcuts', title: 'Shortcuts',
    text: 'Ctrl/Cmd + Z undoes, Ctrl/Cmd + Shift + Z or Ctrl/Cmd + Y redoes, in the timeline and in the paint tool.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'paint', title: 'In the paint tool',
    text: 'The paint tool keeps its own undo history, separate from the timeline. Ctrl/Cmd + Z undoes the last stroke or tool action, Ctrl/Cmd + Shift + Z or Ctrl/Cmd + Y redoes it. Each time you open the tool it starts fresh.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'coalescing', title: 'Slider edits collapse',
    text: 'Dragging a slider records one undo step for the whole gesture, not one per frame, so a single undo reverts the entire drag instead of just the last tick.',
    url: 'docs/undo-redo.html' },

  // privacy
  { cat: 'Privacy', slug: 'privacy', id: 'nothing-leaves', title: 'Nothing leaves your browser',
    text: 'Khuwari is a local tool. The machine learning model downloads once and then runs in your browser, and your images, projects and exports never leave your machine. There are no accounts and no tracking.',
    url: 'docs/privacy.html' }
];
