/* Search index for the Khuwari docs. The hub (docs.html) searches across every
 * category page through this list; each topic links to its subpage. */
window.KHUWARI_DOCS = [
  // getting started
  { cat: 'Getting started', slug: 'getting-started', id: 'what-is', title: 'What is Khuwari?',
    text: 'Khuwari is an animation tool that lives in your browser. You draw or import the poses that matter, drop them on the timeline, and a machine learning model draws everything in between. You do the fun parts; it sweats the boring parts. The model downloads once, and your art never leaves your machine.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'open-app', title: 'Open the app',
    text: 'Open the app straight from the Khuwari website, no install, no account. Or host it yourself: it is a static site, so any file server works. The start screen offers a new project, load, docs, an example project, credits and GitHub.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'project-files', title: 'Project files',
    text: 'Projects save as .khuwari files, one file per project, easy to version and share. They hold your layers, keyframes, gaps and settings. Use File in the toolbar to save one or load one back.',
    url: 'docs/getting-started.html' },

  // interface
  { cat: 'The interface', slug: 'interface', id: 'assets-panel', title: 'Assets panel',
    text: 'Your image library, on the left. Use Add images to bring in art, then drag images onto the timeline to make keyframes. Deleting an image removes it from the library only, never from the timeline.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'preview', title: 'The preview',
    text: 'The big canvas shows the current frame, and the filmstrip under it shows every frame of the animation. Press play, step with the arrow keys, or click a thumb to jump to that frame.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'timeline', title: 'The timeline',
    text: 'Each layer has its own track along the bottom. Keyframes appear as chips; drag a chip to move it and drag its edges to change how long it holds. The space between two keyframes is a gap.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'selection-panel', title: 'Selection panel',
    text: 'The panel on the right shows the details of whatever you have selected: a keyframe, a gap or a color dot. This is where you set times, blend modes, inbetweens and dot properties.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'layers', title: 'Layers',
    text: 'The Layer button in the toolbar opens the layer menu: add a normal or color layer, rename, hide or remove the active one, and reorder them. Layers draw from top to bottom, each with its own keyframes and gaps.',
    url: 'docs/interface.html' },

  // keyframes
  { cat: 'Keyframes', slug: 'keyframes', id: 'add-keyframe', title: 'Add a keyframe',
    text: 'Drag an image from the assets panel onto a layer track, at the moment you want it. The image becomes a keyframe chip, and it will hold that pose until you say otherwise.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'select-inspect', title: 'Select and inspect',
    text: 'Click a chip to select it. The selection panel on the right shows a thumbnail, the exact time, the blend mode, and buttons to replace or delete the frame.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'move-resize', title: 'Move and resize',
    text: 'Drag a chip left or right to change when it happens. Drag its edges to change how long the frame holds before the gap starts. Hold times set the pacing: hold a pose for a beat, or shorten it to a blink.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'set-time', title: 'Set the time exactly',
    text: 'With a keyframe selected, type the time in seconds into the selection panel. Use the playhead and the frame counter to find the exact moment you want.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'replace-delete', title: 'Replace or delete',
    text: 'Replace image swaps in different art while keeping the timing, so you can reuse a shot with a new drawing. Delete removes the keyframe; the Delete or Backspace key does the same thing and is faster.',
    url: 'docs/keyframes.html' },

  // gaps & inbetweens
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'what-is-gap', title: 'What is a gap?',
    text: 'The space between two keyframes on the same layer. Click the gap chip on the timeline to open its options in the right panel; the inbetweens are generated there. The magic (or the weirdness) happens here.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'ml', title: 'Machine learning',
    text: 'The default mode. A machine learning model generates the inbetween frames for the most natural motion on complex art. Khuwari\'s party trick.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'squash', title: 'Squash and stretch',
    text: 'A stylized deformation for cartoon motion, so everything in between squishes and stretches with intent. Pick the amount (or auto), the curve (anticipation, impact, ease or linear) and whether to preserve area or volume.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'none', title: 'No inbetweens',
    text: 'No inbetweens at all. The first keyframe simply holds until the next one starts. Perfect for flashes, cuts and text cards.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'motion-blur', title: 'Motion blur',
    text: 'A per-gap toggle that smears the inbetweens along their motion, easing in and out with the movement. Great for hiding small imperfections in generated frames, and it works on color layers too.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & inbetweens', slug: 'gaps', id: 'regenerate', title: 'Regenerate',
    text: 'Inbetweens regenerate automatically whenever your keyframes change. To force a full refresh, use the regenerate button above the timeline, to the right of the play buttons. Sometimes a little nudge helps.',
    url: 'docs/gaps.html' },

  // color layers
  { cat: 'Color layers', slug: 'color-layers', id: 'what-they-do', title: 'What they do',
    text: 'A color layer holds dots instead of keyframes. Each dot is a smart bucket fill for the layer above: click, and the enclosed area inside the nearest lines fills with color, without touching the drawing.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'add-place', title: 'Add one and place dots',
    text: 'Use the Layer menu and choose Add color layer, then click the canvas to place a dot. New dots remember the last color you used, and you can copy and paste dot properties onto other dots.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'dot-properties', title: 'Dot properties',
    text: 'Each dot has a fill color, a threshold (how strong a line must be to stop the fill) and a grow radius in pixels that tucks the color under soft edges. Tune these per dot.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'gradients', title: 'Gradients',
    text: 'Turn on Gradient to give a dot a gradient instead of a flat fill. Choose the gradient color, its height and its direction (top, bottom, left or right).',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'timing', title: 'Timing',
    text: 'Dots only work during the time you set, with the start and end fields in the right panel or by dragging the dot chip. Outside that window the dot might as well not exist.',
    url: 'docs/color-layers.html' },

  // onion skinning
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'what-it-is', title: 'What it is',
    text: 'Onion skinning shows the frames around the current one so you can see where the motion is heading while you work. Same trick as those light-board desks, minus the physical onions.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'turn-it-on', title: 'Turn it on',
    text: 'The onion button in the transport area toggles it on and off. The small arrow next to it opens the settings popup.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'settings', title: 'Settings',
    text: 'Choose how many frames to show before and after the current one, the ghost opacity, and whether to show the ghosts tinted (pick the color and strength).',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'saved', title: 'Saved automatically',
    text: 'Your onion skin settings are saved in the browser, so they come back the next time you open Khuwari, even after loading a project. Configure the ghosts once and be done with it.',
    url: 'docs/onion-skinning.html' },

  // blend modes
  { cat: 'Blend modes', slug: 'blend-modes', id: 'per-keyframe', title: 'Per keyframe blending',
    text: 'Each keyframe can blend with the layers below it in 16 different ways, from multiply and screen to color and luminosity. Set it in the selection panel. When in doubt, try them all.',
    url: 'docs/blend-modes.html' },

  // export
  { cat: 'Export', slug: 'export', id: 'formats', title: 'Formats',
    text: 'The Export button in the toolbar offers a PNG sequence in a zip, an animated GIF, video in five containers (MP4, WebM, MKV, MOV and MPEG-TS) and the current frame as a single PNG. There is a format for every occasion.',
    url: 'docs/export.html' },
  { cat: 'Export', slug: 'export', id: 'resolution', title: 'Resolution',
    text: 'Pick the export resolution from the export menu. Exports run in the background with a progress bar, and you can stop them if you change your mind.',
    url: 'docs/export.html' },

  // settings
  { cat: 'Settings', slug: 'settings', id: 'fps', title: 'FPS',
    text: 'How many frames per second the timeline plays. Lower values are punchier and cheaper to generate; higher values are smoother. There is no wrong answer, only different amounts of waiting.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'snap', title: 'Snap to frames',
    text: 'Keeps the playhead and keyframes on whole frames, so times stay tidy. Turn it off for free placement. Your call.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'aspect', title: 'Aspect ratio',
    text: 'Follow the first frame, pick a preset such as 16:9 or 1:1, or set a custom size or a manual ratio like 2.35.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'work-size', title: 'Working size',
    text: 'The long edge of the working canvas, from 512 pixels down to 320. Smaller is noticeably faster to generate, and exports still render at full resolution.',
    url: 'docs/settings.html' },

  // keyboard shortcuts
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'playback', title: 'Playback',
    text: 'Space plays or pauses. Left and Right step one frame back or forward.',
    url: 'docs/shortcuts.html' },
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'editing', title: 'Editing',
    text: 'Delete or Backspace deletes the selected keyframe. Ctrl/Cmd + Z undoes, Ctrl/Cmd + Shift + Z or Ctrl/Cmd + Y redoes. Shortcuts are ignored while you are typing.',
    url: 'docs/shortcuts.html' },

  // paint
  { cat: 'Paint', slug: 'paint', id: 'what-it-is', title: 'What it is',
    text: 'A full Krita-style drawing workspace built into Khuwari. Sketch, ink and color on layers with brushes, selection, transform, fill and more, then drop the result straight into the timeline. Paint-made images stay editable: their layers are saved with the project.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'open', title: 'Open the paint tool',
    text: 'Open a blank canvas from the Paint button, or right-click a keyframe and choose Edit in paint to redraw that pose in place. Saved drawings land in the asset library and drag onto the timeline like any image. Editing a library image saves automatically when you close.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'tools', title: 'Tools',
    text: 'Brush, eraser, select, lasso, wand, move, transform, fill, color picker, line, rectangle, ellipse and crop tools, each with a shortcut: B, E, S, L, W, V, T, G, I, U, C. Shortcut letters only work while the paint tool is open.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'brushes', title: 'Brushes',
    text: 'A Krita-style brush preset list with size, opacity, hardness and smoothing (stabilizer) options to keep wobbly strokes in check. Ships with Krita .kpp presets with real brush tips plus MyPaint .myb brushes; drop more files into the brushes folder and they load automatically.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'layers', title: 'Layers',
    text: 'Paint layers each have a thumbnail, visibility, opacity and a blend mode. Add, delete, reorder and merge, double-click to rename, and paint on the selected layer. Layers are saved with the image, so drawings stay editable after save and reopen.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'color', title: 'Color',
    text: 'An HSV color wheel (saturation/value square and hue slider) plus a hex field for exact colors. Colors you actually paint with collect in Recent colors, and the last 8 are saved inside your project file.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'onion', title: 'Onion skin in paint',
    text: 'Turn on onion skin while drawing to see the neighboring frames as ghosts, with the same before/after counts, opacity and tint as the main viewport. The frame scrubber moves the playhead and the ghosts follow it.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'image-ops', title: 'Canvas and image operations',
    text: 'The Image menu flips, rotates or resizes the whole canvas. The crop tool trims to a rectangle. Double-click to re-center, scroll to zoom, and middle-drag or Shift-drag to pan.',
    url: 'docs/paint.html' },
  { cat: 'Paint', slug: 'paint', id: 'save', title: 'Save your drawing',
    text: 'Save to library adds the drawing to the assets panel, where it drags onto the timeline like any image. Repainting a keyframe updates it in place and the gaps around it regenerate; brand-new drawings get named the first time you add them.',
    url: 'docs/paint.html' },

  // camera
  { cat: 'Camera', slug: 'camera', id: 'what-it-is', title: 'What it is',
    text: 'A pan, zoom and rotation for the whole frame, on top of your layers, plus lens and film effects: fisheye, film grain, chromatic aberration, vignette and handheld shake. Non-destructive, and applied to the preview and to exports alike.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'add-key', title: 'Add a camera key',
    text: 'Open the Camera panel, move the playhead, and drag the Pan X, Pan Y, Zoom, Rotation or Effects sliders to add a camera key at that moment. Add key stamps the current values when you want to lock the pose in.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'lane', title: 'The Camera track',
    text: 'Camera keys appear as dots on the Camera row under your layers in the timeline. Drag a dot to retime it, double-click to remove it, or use Remove key with the playhead on one.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'effects', title: 'The Effects sliders',
    text: 'Five effects with intensity from 0 to 100 percent: fisheye warps like a wide lens, chromatic aberration splits red and blue at the edges, film grain adds a seeded speckle, vignette darkens the corners, and handheld shake adds a wobble with its own speed slider. Each blends between keys.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'interpolation', title: 'Between keys',
    text: 'Every camera value, transforms and effects alike, blends smoothly from key to key. Two keys make a slow push-in or pull-out, or ease an effect in and out. Space your keys to shape the easing.',
    url: 'docs/camera.html' },
  { cat: 'Camera', slug: 'camera', id: 'export', title: 'Applied to exports',
    text: 'The camera is part of the final composite, so every exported frame includes it, lens effects and all. Use it with squash, motion blur and color layers like the rest of the frame.',
    url: 'docs/camera.html' },

  // audio
  { cat: 'Audio', slug: 'audio', id: 'what-it-is', title: 'What it is',
    text: 'A scratch track for timing: load a sound file and it plays in sync with the timeline so you can animate to the beat or to dialogue. It guides you; it does not appear in the export.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'load-remove', title: 'Load and manage audio',
    text: 'The Audio panel in the right column loads a sound file, mutes it without removing it, or removes it. Load and Remove swap: Load shows when there is no audio, Remove when there is.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'waveform', title: 'The waveform lane',
    text: 'Once audio is loaded, a green waveform appears in a lane under the timeline, aligned with the same time ruler as your keyframes. Click anywhere in it to jump the playhead there.',
    url: 'docs/audio.html' },
  { cat: 'Audio', slug: 'audio', id: 'saved', title: 'Saved with the project',
    text: 'The audio file is stored inside the .khuwari project, so it comes back when you reopen the file, no hunting for the sound file again. Everything stays on your machine.',
    url: 'docs/audio.html' },

  // undo & redo
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'undo-redo', title: 'Undo and redo',
    text: 'The transport at the bottom of the timeline has Undo and Redo buttons. Everything you do to keyframes, gaps, layers, dots, camera and audio lands on the history stack. Try things; that is the point of undo.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'shortcuts', title: 'Shortcuts',
    text: 'Ctrl/Cmd + Z undoes, Ctrl/Cmd + Shift + Z or Ctrl/Cmd + Y redoes, in the timeline and in the paint tool.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'paint', title: 'In the paint tool',
    text: 'The paint tool keeps its own history, separate from the timeline. Each time you open the tool it starts fresh, so there is no undoing yesterday\'s strokes. Plan accordingly.',
    url: 'docs/undo-redo.html' },
  { cat: 'Undo & redo', slug: 'undo-redo', id: 'coalescing', title: 'Slider edits collapse',
    text: 'Dragging a slider records one undo step for the whole gesture, not one per frame, so one undo reverts the entire drag instead of just the last tick. Undo stays one step ahead of you.',
    url: 'docs/undo-redo.html' },

  // privacy
  { cat: 'Privacy', slug: 'privacy', id: 'nothing-leaves', title: 'Nothing leaves your browser',
    text: 'Khuwari is a free and open source tool that runs entirely in your browser: no server, no backend, no cloud. Your images, projects and exports never leave your machine, there are no accounts and no tracking, and the only model that ever sees your art is the one on your computer.',
    url: 'docs/privacy.html' }
];